### ISSUE TITLE
Project is unavailable on JitPack.io

### ISSUE THREAD

**Issue by amineMpdam** [cdflynn/crossview#4]
For some reason my AndroidStudio can't resolve the library !!
ps: great work by the way ;)

**Comment by jitpack-io** [comment]
Tried with these coordinates and it works: https://jitpack.io/#cdflynn/crossview/3e691ef16e
Would be nicer with a GitHub release though.

**Comment by cdflynn** [comment]
This is now available on jitpack.io as a release version, and the `README` has been updated with instructions for gradle.
Thank you!

**Comment by amineMpdam** [comment]
Great :) thanks 
Can't wait to try it out
Keep up the good work (y)
