### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by jitpack-io** [cdflynn/crossview#5]
Hi!

Would be great to have a GitHub release of crossview so that its easer to install as a gradle dependency.
Right now it works with a commit id https://jitpack.io/#cdflynn/crossview/3e691ef16e

**Comment by cdflynn** [comment]
Thank you!
I've tagged `v1.0` and there is now a release here on github.
https://github.com/cdflynn/crossview/releases

**Comment by jitpack-io** [comment]
Awesome! It works great https://jitpack.io/#cdflynn/crossview/v1.0 

Happy to submit a PR with a badge and install instructions if you are interested.

**Comment by cdflynn** [comment]
@jitpack-io Feel free, that'd be great!
