### ISSUE TITLE
How to change X to a tick icon?

### ISSUE THREAD

**Issue by MIkeeJY** [cdflynn/crossview#8]
I need to change X to √ ，I don't know how to draw it...Help me plz..

**Comment by cdflynn** [comment]
The `X` and `+` are drawn directly to the canvas as a pair of lines, defined by their endpoints.  You can see the endpoint I've defined for the lines, as a pair of arcs:

``` java
    // Arcs that define the set of all points between which the two lines are drawn
    // Names (top, bottom, etc) are from the reference point of the "plus" configuration.
    private Path mArcTop;
    private Path mArcBottom;
    private Path mArcLeft;
    private Path mArcRight;
```

inside `onDraw()`, I draw a line between some point on each arc, defined by a percentage of the arc's length.

With the basics out of the way, what you're asking for is a new set of arcs (or rather, `Path`s) between which do draw each line as it transitions from check to cross.  It can certainly be done, though it's not a trivial change.

**Comment by MIkeeJY** [comment]
I got it,thx man <3
